// Generated by Pricing Dashboard
window.PRICING_DATA = {
  "rate": 328.4,
  "bulk": {
    "5": 10,
    "10": 15,
    "20": 20
  },
  "membership": [
    {
      "id": "creator",
      "name": "Creator",
      "price": 15000,
      "days": 30,
      "videosPerDay": 1,
      "maxMinutes": 3,
      "normalPerVideo": 800,
      "note": "Up to 1 video per day · maximum 3 minutes per video"
    },
    {
      "id": "pro",
      "name": "Pro",
      "price": 28000,
      "days": 30,
      "videosPerDay": 2,
      "maxMinutes": 5,
      "normalPerVideo": 1000,
      "note": "Up to 2 videos per day · maximum 5 minutes per video"
    }
  ],
  "video": [
    {
      "id": "basic",
      "name": "Basic Edit",
      "price": 800,
      "duration": "Up to 1 min",
      "requirement": "Basic",
      "delivery": "1-2 days"
    },
    {
      "id": "standard",
      "name": "Standard Edit",
      "price": 2000,
      "duration": "Up to 5 min",
      "requirement": "Standard",
      "delivery": "2-3 days"
    },
    {
      "id": "premium",
      "name": "Premium Visual",
      "price": 5000,
      "duration": "Up to 10 min",
      "requirement": "Advanced",
      "delivery": "3-4 days"
    }
  ],
  "graphic": [
    {
      "id": "cv",
      "name": "CV / Resume",
      "price": 1800,
      "duration": "1 design",
      "requirement": "Basic",
      "delivery": "1-2 days"
    },
    {
      "id": "poster",
      "name": "Poster / Flyer",
      "price": 2250,
      "duration": "1 design",
      "requirement": "Standard",
      "delivery": "1-2 days"
    },
    {
      "id": "book",
      "name": "Book Cover",
      "price": 2700,
      "duration": "1 cover",
      "requirement": "Advanced",
      "delivery": "1-2 days"
    },
    {
      "id": "social",
      "name": "Social Media Post",
      "price": 1250,
      "duration": "1 design",
      "requirement": "Basic",
      "delivery": "24–48 hours"
    },
    {
      "id": "thumbnail",
      "name": "Thumbnail",
      "price": 1250,
      "duration": "1 design",
      "requirement": "Basic",
      "delivery": "24–48 hours"
    },
    {
      "id": "card",
      "name": "Business Card",
      "price": 1000,
      "duration": "1 design",
      "requirement": "Basic",
      "delivery": "1-2 days"
    }
  ]
};
